spring:
  application:
    name: tax-api-system

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect


  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:h2:mem:taxapp;
    driver-class-name: org.h2.Driver
    username: sa
  #    password: password

  sql:
    init:
      platform: h2
      schema-locations: classpath:schema-h2.sql

excel:
  sample:
    location: classpath:sample/excel/sample.xlsx

#logging:
#  level:
#    org:
#      springframework:
#        jdbc:
#          core:
#            JdbcTemplate: DEBUG
#            StatementCreatorUtils: TRACE